// ELEVATE TNA demo data — single denormalized table (29 Training Needs).
export default [
  {
    "Row_ID": "ROW-0001",
    "TNA_ID": "TNA-0001",
    "Impact_ID": "IMP-0001",
    "Module_ID": "MOD-013",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Global vs. Local Mandates",
    "Description_As_Is": "HSPs handle healthcare content approval locally below the CHF 50k spend threshold.",
    "Description_To_Be": "All healthcare content will route through the Global MLR queue for approval.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Friction | Heatmap",
    "Source_Quote": "PJ pushed back, saying this fundamentally changes the HSP role",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Global vs. Local Mandates",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Coaching",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Global vs. Local Mandates — Primary Point of Contact",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "Coaching (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner",
    "Module_TNA_Count": 1,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 3,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0002",
    "TNA_ID": "TNA-0002",
    "Impact_ID": "IMP-0002",
    "Module_ID": "MOD-014",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Omnichannel / Digital Engagement Workstream",
    "Description_As_Is": "Urgent competitive responses are currently handled and approved locally.",
    "Description_To_Be": "Requires an undefined exception path in the centralized Global MLR queue.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "Sven confirmed there is no current owner for the MLR exception path",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Omnichannel / Digital Engagement Workstream",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "E-learning",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Omnichannel / Digital Engagement Workstream — Primary Point of Contact",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "E-learning (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner",
    "Module_TNA_Count": 1,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 14,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0003",
    "TNA_ID": "TNA-0003",
    "Impact_ID": "IMP-0003",
    "Module_ID": "MOD-011",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i8 First Mover",
    "Affiliate": "IT",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Field Digital Engagement Skills",
    "Description_As_Is": "Operating efficiently in current standard interface systems.",
    "Description_To_Be": "Vault 3.0 interface requires an extended half-day in-person training session to adopt.",
    "Change_Impact": "Medium",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "She estimates a half-day in-person session is required",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field Digital Engagement Skills",
    "Current_Proficiency": 2,
    "Target_Proficiency": 3,
    "Proficiency_Gap": 1,
    "Training_Type": "Workshop",
    "Format": "In-person",
    "Estimated_Hours": 2,
    "Sequencing": "Concurrent",
    "Priority": "Medium",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Coaching Certification & Field Skills",
    "Module_Total_Hours": 8,
    "Module_Delivery_Method": "Workshop (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 2,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "MOD-010",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 14,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0004",
    "TNA_ID": "TNA-0004",
    "Impact_ID": "IMP-0004",
    "Module_ID": "MOD-010",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i8",
    "Affiliate": "Global",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Field / Personal Engagement",
    "Description_As_Is": "Relying on traditional, slower adoption cycles for new platform rollouts.",
    "Description_To_Be": "Adapting to the new platform interface via a phased adoption window.",
    "Change_Impact": "Medium",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "German affiliates traditionally take longer to adopt new platforms",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field / Personal Engagement",
    "Current_Proficiency": 2,
    "Target_Proficiency": 3,
    "Proficiency_Gap": 1,
    "Training_Type": "E-learning",
    "Format": "In-person",
    "Estimated_Hours": 2,
    "Sequencing": "Concurrent",
    "Priority": "Medium",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field Engagement Adaptation",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "E-learning (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 5,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0005",
    "TNA_ID": "TNA-0005",
    "Impact_ID": "IMP-0005",
    "Module_ID": "MOD-008",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i7",
    "Affiliate": "FR",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Mindset & Cultural Sentiment",
    "Change_Component": "Digital Agility & Resilience",
    "Description_As_Is": "Utilizing a similar interface in their current internal tooling.",
    "Description_To_Be": "Transitioning to the new interface with minimal expected friction.",
    "Change_Impact": "Low",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "French Healthcare System Partners already use a similar interface",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital Agility & Resilience",
    "Current_Proficiency": 3,
    "Target_Proficiency": 2,
    "Proficiency_Gap": 0,
    "Training_Type": "Coaching",
    "Format": "In-person",
    "Estimated_Hours": 3,
    "Sequencing": "Post-go-live",
    "Priority": "Low",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital Agility & Resilience — Primary Point of Contact",
    "Module_Total_Hours": 14,
    "Module_Delivery_Method": "Coaching (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 4,
    "Module_Priority": "High",
    "Module_Sequencing": "Post-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Post-go-live",
    "Journey_Phase_Weeks": "Week 5 to 21",
    "Journey_Phase_Hours": 20,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0006",
    "TNA_ID": "TNA-0006",
    "Impact_ID": "IMP-0008",
    "Module_ID": "MOD-004",
    "Journey_ID": "JNY-001",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "CRM Specialist",
    "Persona": "Admin",
    "Persona_Color": "#A65D3D",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Data Stewardship & Governance",
    "Description_As_Is": "Responsible for local vendor master data entries.",
    "Description_To_Be": "Vendor master ownership shifts to centralized governance.",
    "Change_Impact": "Medium",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "vendor master ownership shifts to centralized governance",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Data Stewardship & Governance",
    "Current_Proficiency": 2,
    "Target_Proficiency": 3,
    "Proficiency_Gap": 1,
    "Training_Type": "Coaching",
    "Format": "Virtual",
    "Estimated_Hours": 2,
    "Sequencing": "Concurrent",
    "Priority": "Medium",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Data Stewardship & Governance — Admin",
    "Module_Total_Hours": 2,
    "Module_Delivery_Method": "Coaching (Virtual)",
    "Module_Roles_Covered": "CRM Specialist",
    "Module_TNA_Count": 1,
    "Module_Priority": "Medium",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Admin",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 26,
    "Position_In_Phase": 4,
    "Journey_Total_Hours": 30,
    "Journey_Timeline_Weeks": 10,
    "Journey_Modules_Count": 5,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0007",
    "TNA_ID": "TNA-0007",
    "Impact_ID": "IMP-0012",
    "Module_ID": "MOD-001",
    "Journey_ID": "JNY-002",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Data Analyst",
    "Persona": "BI & Analytics",
    "Persona_Color": "#1A8A8F",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Advanced Data & Analytics Literacy",
    "Description_As_Is": "Operating with standard dashboard consumption skills.",
    "Description_To_Be": "Expected to demonstrate new analytical interpretation competencies on weekly data.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "interpretation is a new analytical competency for many of his Data Analysts",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Advanced Data & Analytics Literacy",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "Self-paced + Labs",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Analytics Interpretation — BI & Analytics",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "Workshop (Self-paced + Labs)",
    "Module_Roles_Covered": "Data Analyst | Data Scientist",
    "Module_TNA_Count": 3,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "BI & Analytics",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -4 to -1",
    "Journey_Phase_Hours": 16,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 22,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0008",
    "TNA_ID": "TNA-0008",
    "Impact_ID": "IMP-0014",
    "Module_ID": "MOD-006",
    "Journey_ID": "JNY-002",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "IT Developer",
    "Persona": "BI & Analytics",
    "Persona_Color": "#1A8A8F",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Digital & Omnichannel Ownership",
    "Description_As_Is": "Handling standard BAU technical development work.",
    "Description_To_Be": "Developers absorb dashboard build work concurrently with BAU.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap | Pressure | Friction",
    "Source_Quote": "The team is at capacity. There is friction between Younes's team and Anika's team",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital & Omnichannel Ownership",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Coaching",
    "Format": "Self-paced + Labs",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital & Omnichannel Ownership — BI & Analytics",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "Coaching (Self-paced + Labs)",
    "Module_Roles_Covered": "IT Developer",
    "Module_TNA_Count": 1,
    "Module_Priority": "High",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "BI & Analytics",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 6,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 22,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0009",
    "TNA_ID": "TNA-0009",
    "Impact_ID": "IMP-0016",
    "Module_ID": "MOD-003",
    "Journey_ID": "JNY-001",
    "Business_Archetype": "i8 First Mover",
    "Affiliate": "IT",
    "Role": "Data Administrator",
    "Persona": "Admin",
    "Persona_Color": "#A65D3D",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Customer Service Workstream",
    "Description_As_Is": "Handling established local vendor contract workflows.",
    "Description_To_Be": "Managing all vendor contracts above CHF 25,000 through Global Procurement Queue.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap | Pressure",
    "Source_Quote": "Data Administrator in Milan reported being 'at her limit'",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Customer Service Workstream",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "E-learning",
    "Format": "Virtual",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Customer Service Workstream — Admin",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "E-learning (Virtual)",
    "Module_Roles_Covered": "Data Administrator",
    "Module_TNA_Count": 1,
    "Module_Priority": "High",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Admin",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 26,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 30,
    "Journey_Timeline_Weeks": 10,
    "Journey_Modules_Count": 5,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0010",
    "TNA_ID": "TNA-0010",
    "Impact_ID": "IMP-0017",
    "Module_ID": "MOD-017",
    "Journey_ID": "JNY-001",
    "Business_Archetype": "i7 First Mover",
    "Affiliate": "Global",
    "Role": "CRM Specialist",
    "Persona": "Admin",
    "Persona_Color": "#A65D3D",
    "Change_Category": "Skill & Capability",
    "Change_Component": "System Admin & Support Expertise",
    "Description_As_Is": "Performing standard user provisioning operations.",
    "Description_To_Be": "Performing user provisioning concurrently across Vault 3.0, SSO, and Procurement Queue.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap | Pressure",
    "Source_Quote": "his CRM Specialists are saturated with the SSO migration in parallel",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: System Admin & Support Expertise",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "Virtual",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Multi-Platform Provisioning Mastery",
    "Module_Total_Hours": 12,
    "Module_Delivery_Method": "Workshop (Virtual)",
    "Module_Roles_Covered": "CRM Specialist | IT Support",
    "Module_TNA_Count": 2,
    "Module_Priority": "High",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Admin",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 26,
    "Position_In_Phase": 3,
    "Journey_Total_Hours": 30,
    "Journey_Timeline_Weeks": 10,
    "Journey_Modules_Count": 5,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0011",
    "TNA_ID": "TNA-0011",
    "Impact_ID": "IMP-0018",
    "Module_ID": "MOD-017",
    "Journey_ID": "JNY-001",
    "Business_Archetype": "i7 First Mover",
    "Affiliate": "Global",
    "Role": "IT Support",
    "Persona": "Admin",
    "Persona_Color": "#A65D3D",
    "Change_Category": "Skill & Capability",
    "Change_Component": "System Admin & Support Expertise",
    "Description_As_Is": "Performing standard user provisioning operations.",
    "Description_To_Be": "Performing user provisioning concurrently across Vault 3.0, SSO, and Procurement Queue.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap | Pressure",
    "Source_Quote": "his IT Support are saturated with the SSO migration in parallel",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: System Admin & Support Expertise",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "Virtual",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Multi-Platform Provisioning Mastery",
    "Module_Total_Hours": 12,
    "Module_Delivery_Method": "Workshop (Virtual)",
    "Module_Roles_Covered": "CRM Specialist | IT Support",
    "Module_TNA_Count": 2,
    "Module_Priority": "High",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Admin",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 26,
    "Position_In_Phase": 3,
    "Journey_Total_Hours": 30,
    "Journey_Timeline_Weeks": 10,
    "Journey_Modules_Count": 5,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0012",
    "TNA_ID": "TNA-0012",
    "Impact_ID": "IMP-0020",
    "Module_ID": "MOD-016",
    "Journey_ID": "JNY-001",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Data Administrator",
    "Persona": "Admin",
    "Persona_Color": "#A65D3D",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Service & Support Ownership",
    "Description_As_Is": "Historical localized procurement handling processes.",
    "Description_To_Be": "Absorbing new Procurement workflow without formal change owner on Admin side.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "no formal change owner for the Procurement Queue workflow on the Admin side",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Service & Support Ownership",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Coaching",
    "Format": "Virtual",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Service & Support Ownership — Admin",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "Coaching (Virtual)",
    "Module_Roles_Covered": "Data Administrator",
    "Module_TNA_Count": 1,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Admin",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 26,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 30,
    "Journey_Timeline_Weeks": 10,
    "Journey_Modules_Count": 5,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0013",
    "TNA_ID": "TNA-0013",
    "Impact_ID": "IMP-0021",
    "Module_ID": "MOD-009",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i8 First Mover",
    "Affiliate": "IT",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Field & Medical Accountability",
    "Description_As_Is": "Hired fundamentally as inside sales support.",
    "Description_To_Be": "Shift in job profile expects them to perform advanced field coaching.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "Lina formally requested EUR 80,000 per affiliate in coaching budget",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field & Medical Accountability",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Coaching",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field & Medical Accountability — Primary Point of Contact",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "Coaching (In-person)",
    "Module_Roles_Covered": "Patient Journey Partner",
    "Module_TNA_Count": 1,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0014",
    "TNA_ID": "TNA-0014",
    "Impact_ID": "IMP-0022",
    "Module_ID": "MOD-010",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i8",
    "Affiliate": "ES",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Field / Personal Engagement",
    "Description_As_Is": "Operating in a standard support role.",
    "Description_To_Be": "Expected to learn new platform and absorb new coaching role transition simultaneously.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "Spanish CSRs are being asked to learn Vault 3.0 and absorb the coaching role",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field / Personal Engagement",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "E-learning",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field Engagement Adaptation",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "E-learning (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 5,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0015",
    "TNA_ID": "TNA-0015",
    "Impact_ID": "IMP-0023",
    "Module_ID": "MOD-011",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i7",
    "Affiliate": "FR",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Field Digital Engagement Skills",
    "Description_As_Is": "Lacking formal certification standard for coaching duties.",
    "Description_To_Be": "New coaching role requires defined certification standard for proficiency.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "There is no certification framework defined yet",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field Digital Engagement Skills",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Coaching Certification & Field Skills",
    "Module_Total_Hours": 8,
    "Module_Delivery_Method": "Workshop (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 2,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "MOD-010",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 14,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0016",
    "TNA_ID": "TNA-0016",
    "Impact_ID": "IMP-0024",
    "Module_ID": "MOD-010",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Field / Personal Engagement",
    "Description_As_Is": "Hybrid sales/coaching role already partially established in APAC.",
    "Description_To_Be": "Transitioning smoothly into the formalized global coaching role profile.",
    "Change_Impact": "Low",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "APAC CSRs are transitioning smoothly",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field / Personal Engagement",
    "Current_Proficiency": 2,
    "Target_Proficiency": 2,
    "Proficiency_Gap": 0,
    "Training_Type": "E-learning",
    "Format": "In-person",
    "Estimated_Hours": 1,
    "Sequencing": "Post-go-live",
    "Priority": "Low",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field Engagement Adaptation",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "E-learning (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 5,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0017",
    "TNA_ID": "TNA-0017",
    "Impact_ID": "IMP-0026",
    "Module_ID": "MOD-010",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i7 First Mover",
    "Affiliate": "Global",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Field / Personal Engagement",
    "Description_As_Is": "Operating with significant field engagement and manual interaction autonomy.",
    "Description_To_Be": "Systemic workflows replacing manual operational autonomy.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "LATAM Patient Journey Partners are forming a narrative",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field / Personal Engagement",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "E-learning",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field Engagement Adaptation",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "E-learning (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 5,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0018",
    "TNA_ID": "TNA-0018",
    "Impact_ID": "IMP-0027",
    "Module_ID": "MOD-008",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i7 First Mover",
    "Affiliate": "Global",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Mindset & Cultural Sentiment",
    "Change_Component": "Digital Agility & Resilience",
    "Description_As_Is": "Trusting their own manual workflows.",
    "Description_To_Be": "Forming a cynical narrative and experiencing anxiety regarding operational value.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "72% expressed concern about becoming data entry clerks",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital Agility & Resilience",
    "Current_Proficiency": 3,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 1,
    "Training_Type": "Coaching",
    "Format": "In-person",
    "Estimated_Hours": 4,
    "Sequencing": "Post-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital Agility & Resilience — Primary Point of Contact",
    "Module_Total_Hours": 14,
    "Module_Delivery_Method": "Coaching (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 4,
    "Module_Priority": "High",
    "Module_Sequencing": "Post-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Post-go-live",
    "Journey_Phase_Weeks": "Week 5 to 21",
    "Journey_Phase_Hours": 20,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0019",
    "TNA_ID": "TNA-0019",
    "Impact_ID": "IMP-0028",
    "Module_ID": "MOD-010",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "i7 First Mover",
    "Affiliate": "BR",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Process & Workflow",
    "Change_Component": "Field / Personal Engagement",
    "Description_As_Is": "Managing high-burden local ANVISA filings.",
    "Description_To_Be": "Absorbing global platform transition alongside intense local regulatory pressure.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap | Pressure",
    "Source_Quote": "Brazil PJPs are operating under unique regulatory pressure",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field / Personal Engagement",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "E-learning",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field Engagement Adaptation",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "E-learning (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 5,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -7 to -1",
    "Journey_Phase_Hours": 28,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0020",
    "TNA_ID": "TNA-0020",
    "Impact_ID": "IMP-0029",
    "Module_ID": "MOD-008",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Patient Journey Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Mindset & Cultural Sentiment",
    "Change_Component": "Digital Agility & Resilience",
    "Description_As_Is": "Experiencing high administrative burden from legacy systems.",
    "Description_To_Be": "Auto-routing features perceived positively as reducing administrative load.",
    "Change_Impact": "Low",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "APAC PJPs view Vault 3.0 positively",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital Agility & Resilience",
    "Current_Proficiency": 3,
    "Target_Proficiency": 2,
    "Proficiency_Gap": 0,
    "Training_Type": "Coaching",
    "Format": "In-person",
    "Estimated_Hours": 3,
    "Sequencing": "Post-go-live",
    "Priority": "Low",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital Agility & Resilience — Primary Point of Contact",
    "Module_Total_Hours": 14,
    "Module_Delivery_Method": "Coaching (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 4,
    "Module_Priority": "High",
    "Module_Sequencing": "Post-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Post-go-live",
    "Journey_Phase_Weeks": "Week 5 to 21",
    "Journey_Phase_Hours": 20,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0021",
    "TNA_ID": "TNA-0021",
    "Impact_ID": "IMP-0030",
    "Module_ID": "MOD-008",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Mindset & Cultural Sentiment",
    "Change_Component": "Digital Agility & Resilience",
    "Description_As_Is": "Navigating manual content generation workflows.",
    "Description_To_Be": "Facing fears of role redundancy due to AI-assisted content generation.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "64% of HSPs reported concern about role redundancy due to AI-assisted content",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital Agility & Resilience",
    "Current_Proficiency": 3,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 1,
    "Training_Type": "Coaching",
    "Format": "In-person",
    "Estimated_Hours": 4,
    "Sequencing": "Post-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital Agility & Resilience — Primary Point of Contact",
    "Module_Total_Hours": 14,
    "Module_Delivery_Method": "Coaching (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner | Patient Journey Partner",
    "Module_TNA_Count": 4,
    "Module_Priority": "High",
    "Module_Sequencing": "Post-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Post-go-live",
    "Journey_Phase_Weeks": "Week 5 to 21",
    "Journey_Phase_Hours": 20,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0022",
    "TNA_ID": "TNA-0022",
    "Impact_ID": "IMP-0033",
    "Module_ID": "MOD-005",
    "Journey_ID": "JNY-001",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Data Administrator",
    "Persona": "Admin",
    "Persona_Color": "#A65D3D",
    "Change_Category": "Mindset & Cultural Sentiment",
    "Change_Component": "Data Trust & Reliance",
    "Description_As_Is": "Relying firmly on established local databases.",
    "Description_To_Be": "Required to trust the Global golden record within the harmonized data layer.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Heatmap",
    "Source_Quote": "harmonized data layer requires affiliates to trust the Global golden record",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Data Trust & Reliance",
    "Current_Proficiency": 3,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 1,
    "Training_Type": "Coaching",
    "Format": "Virtual",
    "Estimated_Hours": 4,
    "Sequencing": "Post-go-live",
    "Priority": "High",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Data Trust & Reliance — Admin",
    "Module_Total_Hours": 4,
    "Module_Delivery_Method": "Coaching (Virtual)",
    "Module_Roles_Covered": "Data Administrator",
    "Module_TNA_Count": 1,
    "Module_Priority": "High",
    "Module_Sequencing": "Post-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Admin",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Post-go-live",
    "Journey_Phase_Weeks": "Week 5 to 10",
    "Journey_Phase_Hours": 4,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 30,
    "Journey_Timeline_Weeks": 10,
    "Journey_Modules_Count": 5,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0023",
    "TNA_ID": "TNA-0023",
    "Impact_ID": "IMP-0034",
    "Module_ID": "MOD-015",
    "Journey_ID": "JNY-004",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Healthcare System Partner",
    "Persona": "Primary Point of Contact",
    "Persona_Color": "#0A3D62",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Omnichannel Technical Mastery",
    "Description_As_Is": "Executing traditional, non-AI assisted content workflows.",
    "Description_To_Be": "Requires specialized training to work productively alongside AI-assisted tools.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "Sven took the action to commission an HSP AI-fluency program",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Omnichannel Technical Mastery",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "In-person",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "AI-Assisted Content Authoring",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "Workshop (In-person)",
    "Module_Roles_Covered": "Healthcare System Partner",
    "Module_TNA_Count": 1,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Post-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Primary Point of Contact",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Post-go-live",
    "Journey_Phase_Weeks": "Week 5 to 21",
    "Journey_Phase_Hours": 20,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 62,
    "Journey_Timeline_Weeks": 21,
    "Journey_Modules_Count": 7,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0024",
    "TNA_ID": "TNA-0024",
    "Impact_ID": "IMP-0035",
    "Module_ID": "MOD-001",
    "Journey_ID": "JNY-002",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Data Scientist",
    "Persona": "BI & Analytics",
    "Persona_Color": "#1A8A8F",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Advanced Data & Analytics Literacy",
    "Description_As_Is": "Analyzing legacy dashboard monthly outputs.",
    "Description_To_Be": "Requires expanded analytical interpretation training to manage weekly cadences.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "need expanded analytical interpretation training",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Advanced Data & Analytics Literacy",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "Self-paced + Labs",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Analytics Interpretation — BI & Analytics",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "Workshop (Self-paced + Labs)",
    "Module_Roles_Covered": "Data Analyst | Data Scientist",
    "Module_TNA_Count": 3,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "BI & Analytics",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -4 to -1",
    "Journey_Phase_Hours": 16,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 22,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0025",
    "TNA_ID": "TNA-0025",
    "Impact_ID": "IMP-0036",
    "Module_ID": "MOD-001",
    "Journey_ID": "JNY-002",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Data Analyst",
    "Persona": "BI & Analytics",
    "Persona_Color": "#1A8A8F",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Advanced Data & Analytics Literacy",
    "Description_As_Is": "Analyzing legacy dashboard monthly outputs.",
    "Description_To_Be": "Requires expanded analytical interpretation training to manage weekly cadences.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "need expanded analytical interpretation training",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Advanced Data & Analytics Literacy",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "Self-paced + Labs",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Analytics Interpretation — BI & Analytics",
    "Module_Total_Hours": 16,
    "Module_Delivery_Method": "Workshop (Self-paced + Labs)",
    "Module_Roles_Covered": "Data Analyst | Data Scientist",
    "Module_TNA_Count": 3,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "BI & Analytics",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -4 to -1",
    "Journey_Phase_Hours": 16,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 22,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0026",
    "TNA_ID": "TNA-0026",
    "Impact_ID": "IMP-0037",
    "Module_ID": "MOD-012",
    "Journey_ID": "JNY-005",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Clinical Trials Expert",
    "Persona": "Scientific Expert",
    "Persona_Color": "#2C5F8D",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Field Digital Engagement Skills",
    "Description_As_Is": "Using a separate legacy clinical trials documentation system.",
    "Description_To_Be": "Interface alters significantly, requiring 4-6 hours of platform retraining.",
    "Change_Impact": "Medium",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "Clinical Trials Experts will need 4-6 hours of platform retraining",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Field Digital Engagement Skills",
    "Current_Proficiency": 2,
    "Target_Proficiency": 3,
    "Proficiency_Gap": 1,
    "Training_Type": "Workshop",
    "Format": "Self-paced",
    "Estimated_Hours": 2,
    "Sequencing": "Concurrent",
    "Priority": "Medium",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Field Digital Engagement Skills — Scientific Expert",
    "Module_Total_Hours": 2,
    "Module_Delivery_Method": "Workshop (Self-paced)",
    "Module_Roles_Covered": "Clinical Trials Expert",
    "Module_TNA_Count": 1,
    "Module_Priority": "Medium",
    "Module_Sequencing": "Concurrent",
    "Module_Prerequisites": "",
    "Journey_Persona": "Scientific Expert",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Concurrent",
    "Journey_Phase_Weeks": "Week 0 to 4",
    "Journey_Phase_Hours": 2,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 2,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 1,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0027",
    "TNA_ID": "TNA-0027",
    "Impact_ID": "IMP-0038",
    "Module_ID": "MOD-007",
    "Journey_ID": "JNY-003",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Marketing Specialist",
    "Persona": "Digital",
    "Persona_Color": "#8B5A3C",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Digital & Omnichannel Ownership",
    "Description_As_Is": "Managing standard campaign execution sequentially.",
    "Description_To_Be": "Redefined role requires orchestration of multichannel campaigns.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "fundamental redefinition of the role",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital & Omnichannel Ownership",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Coaching",
    "Format": "Hybrid",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital & Omnichannel Ownership — Digital",
    "Module_Total_Hours": 12,
    "Module_Delivery_Method": "Coaching (Hybrid)",
    "Module_Roles_Covered": "Digital & Multichannel Coordinator | Marketing Specialist",
    "Module_TNA_Count": 2,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Digital",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -4 to -1",
    "Journey_Phase_Hours": 18,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 18,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0028",
    "TNA_ID": "TNA-0028",
    "Impact_ID": "IMP-0039",
    "Module_ID": "MOD-002",
    "Journey_ID": "JNY-003",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Product Manager",
    "Persona": "Digital",
    "Persona_Color": "#8B5A3C",
    "Change_Category": "Skill & Capability",
    "Change_Component": "Advanced Data & Analytics Literacy",
    "Description_As_Is": "Defining product roadmaps without formal analytics tool training.",
    "Description_To_Be": "Required to interpret dashboard outputs to drive roadmap decisions.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "estimates 1-2 hours of training per week for 8 weeks would close the gap",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Advanced Data & Analytics Literacy",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Workshop",
    "Format": "Hybrid",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Analytics Interpretation — Digital",
    "Module_Total_Hours": 6,
    "Module_Delivery_Method": "Workshop (Hybrid)",
    "Module_Roles_Covered": "Product Manager",
    "Module_TNA_Count": 1,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Digital",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -4 to -1",
    "Journey_Phase_Hours": 18,
    "Position_In_Phase": 1,
    "Journey_Total_Hours": 18,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  },
  {
    "Row_ID": "ROW-0029",
    "TNA_ID": "TNA-0029",
    "Impact_ID": "IMP-0050",
    "Module_ID": "MOD-007",
    "Journey_ID": "JNY-003",
    "Business_Archetype": "Global Function",
    "Affiliate": "Global",
    "Role": "Digital & Multichannel Coordinator",
    "Persona": "Digital",
    "Persona_Color": "#8B5A3C",
    "Change_Category": "Roles & Responsibilities",
    "Change_Component": "Digital & Omnichannel Ownership",
    "Description_As_Is": "Coordinating digital campaign execution locally.",
    "Description_To_Be": "Scope expanding to cover full cross-platform orchestration.",
    "Change_Impact": "High",
    "CIA_Confidence": "High",
    "Tags": "Gap | Heatmap",
    "Source_Quote": "significant role expansion that has not been formally captured",
    "Source_Doc": "ELEVATE_Steerco_Transcript_2026-05-12_STRESS_TEST.md.pdf",
    "Source_Run": "Steerco_2026-05-12_STRESS_TEST",
    "Competency_Required": "Demonstrate proficiency in: Digital & Omnichannel Ownership",
    "Current_Proficiency": 2,
    "Target_Proficiency": 4,
    "Proficiency_Gap": 2,
    "Training_Type": "Coaching",
    "Format": "Hybrid",
    "Estimated_Hours": 6,
    "Sequencing": "Pre-go-live",
    "Priority": "Critical",
    "ECL_Stream": "Training",
    "Action_Owner": "TBD",
    "TNA_Status": "Scoped",
    "Module_Name": "Digital & Omnichannel Ownership — Digital",
    "Module_Total_Hours": 12,
    "Module_Delivery_Method": "Coaching (Hybrid)",
    "Module_Roles_Covered": "Digital & Multichannel Coordinator | Marketing Specialist",
    "Module_TNA_Count": 2,
    "Module_Priority": "Critical",
    "Module_Sequencing": "Pre-go-live",
    "Module_Prerequisites": "",
    "Journey_Persona": "Digital",
    "Journey_Affiliate": "Global",
    "Journey_Phase": "Pre-go-live",
    "Journey_Phase_Weeks": "Week -4 to -1",
    "Journey_Phase_Hours": 18,
    "Position_In_Phase": 2,
    "Journey_Total_Hours": 18,
    "Journey_Timeline_Weeks": 8,
    "Journey_Modules_Count": 2,
    "Validation_Status": "Pending"
  }
]
